// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWZ0B4pDoTahmb_bElKcOFBF8taEU4Ec',
    appId: '1:688886286809:web:19317553f6a5e7584071c8',
    messagingSenderId: '688886286809',
    projectId: 'sathyabama-bus-tracker-2259a',
    authDomain: 'sathyabama-bus-tracker-2259a.firebaseapp.com',
    storageBucket: 'sathyabama-bus-tracker-2259a.firebasestorage.app',
    measurementId: 'G-29HBMLYDT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTx1OD7NQX22-9pMsaSrNCz-rOOb0f-AE',
    appId: '1:688886286809:android:d97655182f2518fa4071c8',
    messagingSenderId: '688886286809',
    projectId: 'sathyabama-bus-tracker-2259a',
    storageBucket: 'sathyabama-bus-tracker-2259a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDUKCOsH7YRp7T_rg0epJ3J8W-o-MwiEI',
    appId: '1:688886286809:ios:564d7a35dc74ac464071c8',
    messagingSenderId: '688886286809',
    projectId: 'sathyabama-bus-tracker-2259a',
    storageBucket: 'sathyabama-bus-tracker-2259a.firebasestorage.app',
    iosBundleId: 'com.example.collegeBusTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDUKCOsH7YRp7T_rg0epJ3J8W-o-MwiEI',
    appId: '1:688886286809:ios:564d7a35dc74ac464071c8',
    messagingSenderId: '688886286809',
    projectId: 'sathyabama-bus-tracker-2259a',
    storageBucket: 'sathyabama-bus-tracker-2259a.firebasestorage.app',
    iosBundleId: 'com.example.collegeBusTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGWZ0B4pDoTahmb_bElKcOFBF8taEU4Ec',
    appId: '1:688886286809:web:ed29eece41d078664071c8',
    messagingSenderId: '688886286809',
    projectId: 'sathyabama-bus-tracker-2259a',
    authDomain: 'sathyabama-bus-tracker-2259a.firebaseapp.com',
    storageBucket: 'sathyabama-bus-tracker-2259a.firebasestorage.app',
    measurementId: 'G-31QQBJ73NZ',
  );
}
